feat: Adds dynamic table notices from Atlas
amundsen-io/amundsen pull request #1254
Opened 2021-06-21 20:06 UTC by stswn

### Summary of Changes

In follow up to [#957](https://github.com/amundsen-io/amundsenfrontendlibrary/pull/957) functionality of table notices is extended to allow for defining multiple dynamic notices for each table in Apache Atlas. Notices coming from Atlas are displayed together with config notices in the same fashion.

### Tests

Tests were adjusted to accommodate new data model.

### Documentation

--

2021-06-21 20:06 UTC, stswn commented
@mgorsk1

2021-06-22 07:26 UTC, mgorsk1 requested changes
backend-wise lgtm with just one nit - we might need to release and bump amundsen-common in separate MR

can you please extend unit tests and fill out DCO https://github.com/apps/dco?

cc @Golodhros for frontend stuff

2021-06-22 15:40 UTC, Golodhros commented on frontend/amundsen_application/static/js/pages/TableDetailPage/index.tsx
> +              {notices.map((notice) => (
What if notices is empty?

At this point, I would extract a component here, something like <NoticeList /> and move all the logic inside.

2021-06-22 15:41 UTC, Golodhros commented on frontend/amundsen_application/static/js/pages/TableDetailPage/index.tsx
> +      }));
This doesn't apply to dashboards? Only for tables?

2021-06-22 18:28 UTC, allisonsuarez commented
I think is a good idea to make notices dynamic, however I believe we should make sure this model is reusable for other entities and that we add the metadata proxy method as an interface in base proxy for others to use. Could we maybe open an RFC for this so it can be opened up for discussion?

2021-07-28 02:33 UTC, closed without merging