feat-allow dangerous html based on config variable
amundsen-io/amundsen pull request #1459
Opened 2021-08-25 11:24 UTC by MrwanBaghdad

### Summary of Changes

Added configuration variable to allow rendering of dangerous HTML in the programmatic description for table detail pages

### Tests

### Documentation

The use case is that we'd like to enable embedding in the programmatic descriptions. As the programmatic descriptions are populated by an ingestion pipeline that can validate its safety and is not editable by any web user; a requirement missing in the table description were editing may be allowed and it won't be safe to enable such functionality of rendering dangerous HTML

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [x] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [x] PR includes a summary of changes.
- [ ] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public functions and the classes in the PR contain docstrings that explain what it does

2021-09-13 23:38 UTC, dorianj commented
Do we even need to use `EditableText` for this, given that editable is false? Can we include `ReactMarkdown` directly? I think that would assuage the concern of turning `EditableText` into a footgun?

2021-09-14 16:35 UTC, Golodhros commented
> Do we even need to use `EditableText` for this, given that editable is false? Can we include `ReactMarkdown` directly? I think that would assuage the concern of turning `EditableText` into a footgun?

That makes sense to me!

2022-04-28 19:58 UTC, Golodhros requested changes

2022-04-28 19:58 UTC, Golodhros commented on frontend/amundsen_application/static/js/config/config-utils.ts
> +
We need a basic tests for this

2022-04-28 19:58 UTC, Golodhros commented on frontend/amundsen_application/static/js/config/config-utils.ts
> +export function isProgrammaticDescAllowDangerousHtml(): boolean {
this is a mouthful of name. It is tricky, but I think 'hasHTMLDescription' would work better. Same for the config object field.

2022-04-28 19:58 UTC, Golodhros commented on frontend/amundsen_application/static/js/pages/TableDetailPage/index.tsx
> +        <div className="editable-text">
I am not sure what are we doing here.
You modified <EditableText> to allow for the 'allowDangerousHtml' prop, why using ReactMarkdown here directly?

2022-04-29 09:33 UTC, ozandogrultan commented
@Golodhros I have changed the approach slightly; instead of checking a frontend config variable, now **only programmatic descriptions** always allow dangerous html. This would allow the usage of tags like `iframe` in the programmatic descriptions.

2022-04-29 16:55 UTC, Golodhros commented
We talked about this before @dorianj, what do you think about this change?

2022-05-09 09:02 UTC, ozandogrultan commented
@dorianj @Golodhros Any updates on this pull request? It is a small change which would help our team (and potentially teams which require similar functionality) a lot and would be great to see it merged.

2022-05-20 17:17 UTC, ozandogrultan commented
@dorianj @Golodhros Just bumping this up, our team is still looking forward to seeing this PR getting merged!

2022-05-20 21:20 UTC, Golodhros approved these changes
LGTM

2022-05-20 21:21 UTC, merged