feat introduce s3 support in openlineage extractor
amundsen-io/amundsen pull request #1601
Opened 2021-12-01 07:40 UTC by dechoma

Signed-off-by: dechoma <dominik.choma@gmail.com>

### Summary of Changes
added change allowing to read events from s3
### Tests

### Documentation

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [ ] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [ ] PR includes a summary of changes.
- [ ] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public functions and the classes in the PR contain docstrings that explain what it does

2021-12-07 07:39 UTC, mgorsk1 requested changes

2021-12-07 07:39 UTC, mgorsk1 commented on databuilder/databuilder/extractor/openlineage_extractor.py
> +    def _generate_TableLineage_events(self) -> Any:
please follow pep8 for naming functions

2022-06-18 17:52 UTC, feng-tao commented
@dechoma @mgorsk1 are you still working on this pr? should we close it if not?

2023-02-06 22:48 UTC, Golodhros commented
Closing as abanoned

2023-02-06 22:48 UTC, closed without merging